#####################################################################
# 注意事项
#
# - 环境变量的格式为"键=值"，顶格写，注意等号两边不能有空格，值可以用单引号或者双引号引起来，不引也行（下面的特殊情况必须引起来）
# - 因为环境变量中"#"代表注释，若密码中存在"#"字符的，一定要使用单引号将整个密码引起来，否则解析会在"#"字符前截止，如果密码中存在单双引号的，
#    需要在单双引号前加“\”转义
# - 配置多账户不可省略单引号，且多个账户和密码的格式必须是"<账户1>@<密码1>|<账户2>@<密码2>|<账户3>@<密码3>"，不要有空格，就算有程序也会给你干掉
# 例如 MULTIPLE_ACCOUNTS='<账户1>@<密码1>|<账户2>@<密码2>|<账户3>@<密码3>'
#    注意不要省略“<>”符号，否则无法正确匹配
# - 若你只有单个账户，只配置 FREENOM_USERNAME 和FREENOM_PASSWORD 就够了
# - 单账户和多账户的配置会被合并在一起读取并去重
#####################################################################

# .env 文件版本
ENV_FILE_VERSION='v2.4'

######## 账户配置 帐户配置#########################
#Freenom 账户 Freenom Account
FREENOM_USERNAME=''

#自由密码
FREENOM_PASSWORD=''

# 多账户支持 支持多个账户
MULTIPLE_ACCOUNTS=''

# 【可选】 自由代理 [可选] 自由代理，例如 http://127.0.0.1:1081 或 socks5：//127.0.0.1：1080
FREENOM_PROXY=''
######### end 账户配置#########################

########## 通知邮件配置 电子邮件配置#########################
# 机器人邮箱账户
MAIL_USERNAME=''

# 机器人邮箱密码（Gmail填密码，QQ邮箱或163邮箱填授权码） 机器人邮箱的密码
MAIL_PASSWORD=''

# 用于接收通知的邮箱
到=''

# 是否启用邮件推送功能 1：启用 0：不启用 是否启用电子邮件推送功能 1： 启用 0： 未启用
MAIL_ENABLE=0

# 【可选】 自定义邮箱配置
# 如果你想使用除“QQ邮箱、163邮箱、Gmail、Outlook邮箱”以外的邮箱或者自建邮箱服务作为机器人邮箱，可以自定义邮箱配置，否则请不要配置这些项
#如果要使用“QQ邮箱，163邮箱，Gmail，Outlook邮箱”或自建邮箱服务以外的邮箱作为机器人邮箱，则可以自定义邮箱配置，否则请不要配置这些项目。

# 【可选】 SMTP 服务器 [可选] SMTP 服务器 smtp.gmail.com
MAIL_HOST=''

# 【可选】 SMTP 端口号，一般是 587 或者 465
MAIL_PORT=''

# 【可选】 邮件加密方式，一般是 tls 或者 ssl 或者 starttls [Optional] 邮件加密方法，通常 tls 或 ssl 或 starttls
MAIL_ENCRYPTION=''

# 结束 自定义邮箱配置 自定义电子邮件配置结束

##########结束 通知邮件配置#########################

#################################
# 通过 电报机器人 发送通知消息 通过电报机器人发送消息

# 你的 chat_id，通过发送“/start”给 @userinfobot 可以获取自己的 chat_id @userinfobot id
TELEGRAM_CHAT_ID=''

# 你的 电报机器人 的令牌 令牌 为您的电报机器人
TELEGRAM_BOT_TOKEN=''

# 【可选】 电报代理 [可选] 电报代理，例如 http://127.0.0.1:1081 或 socks5：//127.0.0.1：1080
TELEGRAM_PROXY=''

# 【可选】 自建 Telegram 反向代理地址，不明白则请忽略此配置项，保持默认即可
# 参考：https://web.archive.org/web/20220221035315/https://hostloc.com/thread-805441-1-1.html
# 只要是一个合法的网址即可，程式会自动提取网址的主机部分。例如 https://xxx.xx.workers.dev/ 或 xxx.xx.xx
CUSTOM_TELEGRAM_HOST='api.telegram.org'

# 是否启用 电报机器人 功能 1：启用 0：不启用 是否启用 电报机器人功能 1： 启用 0： 未启用
TELEGRAM_BOT_ENABLE=0
##################################

########### 企业微信#########################
# 企业 ID 企业 ID
WECHAT_CORP_ID=''

# 企业微信应用的凭证密钥
WECHAT_CORP_SECRET=''

# 应用 ID
WECHAT_AGENT_ID=''

# 是否启用企业微信送信功能 1：启用 0：不启用
WECHAT_ENABLE=0
######## end 企业微信#########################

##################################
#Server 酱的 SendKey
SCT_SEND_KEY=''

# 是否启用 Server 酱 送信功能 1：启用 0：不启用 是否启用 ServerChan 消息功能 1： 启用 0： 未启用
SCT_ENABLE=0
##################################

##########Bark 送信#########################
#Bark key 打开 Bark App，注册设备后看到的密钥 打开 Bark App，注册设备并查看密钥
# 支持直接粘贴 “https://api.day.app/xxx/ 这里改成你自己的推送内容” 这类文本，程序会自动从中提取有效的 Bark https://api.day.app/xxx/ key
BARK_KEY=''

#Bark域名 默认是 Bark 作者提供的服务，建议自建 Bark URL 默认为 Bark 作者提供的服务器，建议自行构建
BARK_URL='https://api.day.app'

#Bark 其它相关参数（保持默认即可）
BARK_IS_ARCHIVE=''
BARK_GROUP='FreeNom'
BARK_LEVEL=“活动”
BARK_ICON='https://q2.qlogo.cn/headimg_dl?dst_uin=593198779&spec=100'
BARK_JUMP_URL=''
BARK_SOUND='gotosleep'

# 是否启用 Bark 推送消息 1：启用 0：不启用 是否启用 Bark 推送消息 1： 启用 0： 不启用
BARK_ENABLE=0
########end Bark 送信#########################

# 通知频率 0：仅当有续期操作的时候 1：每次执行
NOTICE_FREQ=1

# 是否验证服务器证书 1：验证 0：不验证
VERIFY_SSL=0

# 是否开启 Debug 模式 1：开启 0：关闭 是否打开
调试 = 0

# 检测是否有新版本可用，发现新版本时推送消息通知 1：开启 0：关闭
NEW_VERSION_DETECTION=1

# 应用语言配置 应用语言配置，支持的值为 zh 或 en，zh 表示中文，en 表示英语
语言=zh

# 送信时是否显示服务器信息 1：显示 0：不显示 发送消息时是否显示服务器信息
SHOW_SERVER_INFO=0
